platform :ios, '5.0'

target :__TESTING__Local, :exclusive => true do
	pod 'AFNetworking', '~> 1.3.0'
	pod 'Reachability'
	pod 'MBProgressHUD'
	pod 'SSToolkit'
	pod 'SSKeychain'
	pod 'SVPullToRefresh'
	pod 'EXHelpers', :git => 'https://github.com/exister/EXHelpers.git'
	pod 'SDWebImage'
	pod 'DAKeyboardControl'
	pod 'CocoaLumberjack'
	pod 'HockeySDK', :podspec => 'Specs/HockeySDK.podspec'
	pod 'DB5', :git => 'https://github.com/exister/DB5.git'
	pod 'TMCache'
	pod 'UITableView-NXEmptyView'
##########################################################
    pod 'Reveal-iOS-SDK'
    pod 'OHHTTPStubs'
end

target :__TESTING__Release, :exclusive => true do
	pod 'AFNetworking', '~> 1.3.0'
    pod 'Reachability'
    pod 'MBProgressHUD'
    pod 'SSToolkit'
    pod 'SSKeychain'
    pod 'SVPullToRefresh'
    pod 'EXHelpers', :git => 'https://github.com/exister/EXHelpers.git'
    pod 'SDWebImage'
    pod 'DAKeyboardControl'
    pod 'CocoaLumberjack'
    pod 'HockeySDK', :podspec => 'Specs/HockeySDK.podspec'
    pod 'DB5', :git => 'https://github.com/exister/DB5.git'
    pod 'TMCache'
    pod 'UITableView-NXEmptyView'
##########################################################
    pod 'FlurrySDK'
end

target :__TESTING__Beta, :exclusive => true do
	pod 'AFNetworking', '~> 1.3.0'
    pod 'Reachability'
    pod 'MBProgressHUD'
    pod 'SSToolkit'
    pod 'SSKeychain'
    pod 'SVPullToRefresh'
    pod 'EXHelpers', :git => 'https://github.com/exister/EXHelpers.git'
    pod 'SDWebImage'
    pod 'DAKeyboardControl'
    pod 'CocoaLumberjack'
    pod 'HockeySDK', :podspec => 'Specs/HockeySDK.podspec'
    pod 'DB5', :git => 'https://github.com/exister/DB5.git'
    pod 'TMCache'
    pod 'UITableView-NXEmptyView'
##########################################################
    pod 'TestFlightSDK'
end